### ISSUE TITLE
Test-01: CWRC entity previews - "page not found" error

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-PublicEntityDialogs#27]
I think this on you, @ajmacdonald

**Comment by ajmacdonald** [comment]
The issue is that the entity root isn't being set properly: https://github.com/cwrc/Islandora-CWRC-Writer/blob/master/js/app.js#L4
It is currently `cwrc.setEntityRoot('https://test-01.cwrc.ca');` but should be `cwrc.setEntityRoot('https://test-01.cwrc.ca/islandora/object');`

I can't SSH into test-01 so I can't update the file myself.

**Comment by ilovan** [comment]
fixed
